name: residualvm
base: core18
license: GPL-2.0
adopt-info: residualvm
summary: Residualvm
description: |
    ResidualVM is a cross-platform 3D game interpreter which allows you to play LucasArts' Lua-based 3D adventures: Grim Fandango and Escape from Monkey Island, provided you already have their data files.
    
    ResidualVM just replaces the executables shipped with the games, allowing you to play them on systems for which they were never designed! 
confinement: strict
grade: stable

apps:
  residualvm:
    command: desktop-launch $SNAP/bin/residualvm
    plugs:
      - x11
      - wayland
      - unity7
      - opengl
      - audio-playback
      - joystick
      - removable-media
      - home

parts:
  residualvm:
    plugin: autotools
    after: [desktop-glib-only]
    source: https://github.com/residualvm/residualvm.git
    override-build: |
      last_committed_tag="$(git tag | grep ^0 | sort -V | tail -n 1)"
      trimmed_tag="$(echo $last_committed_tag | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')"
      last_released_tag="$(snap info residualvm | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${trimmed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version ${last_committed_tag}
      else
        snapcraftctl set-version $(git -C ../src describe | sed 's/desc\///')
      fi
      snapcraftctl build
      
    plugin: autotools
    configflags:
      - --enable-release
      - --disable-debug

    build-packages:
      - g++
      - build-essential
      - libsdl2-dev
      - libogg-dev
      - libflac-dev
      - libflac++-dev
      - libmad0-dev
      - libglew-dev
      - libmpeg2-4-dev
      - libpng-dev
      - libjpeg9-dev
      - libfreetype6-dev
      - libharfbuzz-dev
      - zlib1g-dev
    stage-packages:
      - libstdc++6
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libwayland-egl1-mesa
      - libsdl2-2.0-0 
      - libglew2.0
      - libmpeg2-4
      - libpng16-16
      - libjpeg9
      - libvorbis0a
      - libvorbisfile3
      - libflac8
      - libflac++6v5
      - libmad0
      - libdbusmenu-glib4
      - libunity-protocol-private0
      - libunity9
      - libfreetype6
      - zlib1g
      - locales-all

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

